# Generated by Django 4.2 on 2023-05-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_title_post_username_post_yazar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userName',
        ),
    ]
