# Generated by Django 4.2 on 2023-05-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_toplulukolusturma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.toplulukolusturma'),
        ),
    ]
