# Generated by Django 4.2 on 2023-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_backimage_profile_bio_profile_created_at_and_more'),
        ('posts', '0008_post_dislike_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='user.profile', verbose_name='Begenmeyenler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, to='user.profile', verbose_name='Begenenler'),
        ),
    ]
