# Generated by Django 4.1.7 on 2023-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backimage',
            field=models.FileField(null=True, upload_to='profiles/', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Merhaba', max_length=500, null=True, verbose_name='Hakkinda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Olusturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profiles/default.jpg', null=True, upload_to='profiles/', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='isim'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Soyisim'),
        ),
    ]
